# German message translation file for plpython
# Copyright (C) 2009 - 2016 PostgreSQL Global Development Group
# This file is distributed under the same license as the PostgreSQL package.
# Peter Eisentraut <peter_e@gmx.net>, 2009 - 2016.
#
# Use these quotes: »%s«
#
msgid ""
msgstr ""
"Project-Id-Version: PostgreSQL 9.5\n"
"Report-Msgid-Bugs-To: pgsql-bugs@postgresql.org\n"
"POT-Creation-Date: 2016-07-04 20:37+0000\n"
"PO-Revision-Date: 2016-07-04 19:11-0400\n"
"Last-Translator: Peter Eisentraut <peter_e@gmx.net>\n"
"Language-Team: German <peter_e@gmx.net>\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"

#: plpy_cursorobject.c:101
#, c-format
msgid "plpy.cursor expected a query or a plan"
msgstr "plpy.cursor hat eine Anfrage oder einen Plan erwartet"

#: plpy_cursorobject.c:179
#, c-format
msgid "plpy.cursor takes a sequence as its second argument"
msgstr "plpy.cursor nimmt eine Sequenz als zweites Argument"

#: plpy_cursorobject.c:195 plpy_spi.c:229
#, c-format
msgid "could not execute plan"
msgstr "konnte Plan nicht ausführen"

#: plpy_cursorobject.c:198 plpy_spi.c:232
#, c-format
msgid "Expected sequence of %d argument, got %d: %s"
msgid_plural "Expected sequence of %d arguments, got %d: %s"
msgstr[0] "Sequenz aus %d Argument erwartet, aber %d erhalten: %s"
msgstr[1] "Sequenz aus %d Argumenten erwartet, aber %d erhalten: %s"

#: plpy_cursorobject.c:354
#, c-format
msgid "iterating a closed cursor"
msgstr "Iteration mit einem geschlossenen Cursor"

#: plpy_cursorobject.c:362 plpy_cursorobject.c:427
#, c-format
msgid "iterating a cursor in an aborted subtransaction"
msgstr "Iteration mit einem Cursor in einer abgebrochenen Transaktionen"

#: plpy_cursorobject.c:419
#, c-format
msgid "fetch from a closed cursor"
msgstr "Lesen aus einem geschlossenen Cursor"

#: plpy_cursorobject.c:467 plpy_spi.c:438
#, c-format
msgid "query result has too many rows to fit in a Python list"
msgstr "Anfrageergebnis hat zu viele Zeilen, um in eine Python-Liste zu passen"

#: plpy_cursorobject.c:508
#, c-format
msgid "closing a cursor in an aborted subtransaction"
msgstr "Schließen eines Cursors in einer abgebrochenen Subtransaktion"

#: plpy_elog.c:127 plpy_elog.c:128 plpy_plpymodule.c:527
#, c-format
msgid "%s"
msgstr "%s"

#: plpy_exec.c:140
#, c-format
msgid "unsupported set function return mode"
msgstr "nicht unterstützter Rückgabemodus für Funktion mit Mengenergebnis"

#: plpy_exec.c:141
#, c-format
msgid "PL/Python set-returning functions only support returning one value per call."
msgstr "PL/Python unterstützt für Funktionen mit Mengenergebnis nur das Zurückgeben von einem Wert pro Aufruf."

#: plpy_exec.c:154
#, c-format
msgid "returned object cannot be iterated"
msgstr "zurückgegebenes Objekt kann nicht iteriert werden"

#: plpy_exec.c:155
#, c-format
msgid "PL/Python set-returning functions must return an iterable object."
msgstr "PL/Python-Funktionen mit Mengenergebnis müssen ein iterierbares Objekt zurückgeben."

#: plpy_exec.c:169
#, c-format
msgid "error fetching next item from iterator"
msgstr "Fehler beim Auslesen des nächsten Elements vom Iterator"

#: plpy_exec.c:210
#, c-format
msgid "PL/Python function with return type \"void\" did not return None"
msgstr "PL/Python-Funktion mit Rückgabetyp »void« hat nicht None zurückgegeben"

#: plpy_exec.c:374 plpy_exec.c:400
#, c-format
msgid "unexpected return value from trigger procedure"
msgstr "unerwarteter Rückgabewert von Triggerprozedur"

#: plpy_exec.c:375
#, c-format
msgid "Expected None or a string."
msgstr "Erwartete None oder eine Zeichenkette."

#: plpy_exec.c:390
#, c-format
msgid "PL/Python trigger function returned \"MODIFY\" in a DELETE trigger -- ignored"
msgstr "PL/Python-Funktion gab in einem DELETE-Trigger \"MODIFY\" zurück -- ignoriert"

#: plpy_exec.c:401
#, c-format
msgid "Expected None, \"OK\", \"SKIP\", or \"MODIFY\"."
msgstr "Erwartete None, \"OK\", \"SKIP\" oder \"MODIFY\"."

#: plpy_exec.c:482
#, c-format
msgid "PyList_SetItem() failed, while setting up arguments"
msgstr "PyList_SetItem() fehlgeschlagen, beim Einrichten der Argumente"

#: plpy_exec.c:486
#, c-format
msgid "PyDict_SetItemString() failed, while setting up arguments"
msgstr "PyDict_SetItemString() fehlgeschlagen, beim Einrichten der Argumente"

#: plpy_exec.c:498
#, c-format
msgid "function returning record called in context that cannot accept type record"
msgstr "Funktion, die einen Record zurückgibt, in einem Zusammenhang aufgerufen, der Typ record nicht verarbeiten kann"

#: plpy_exec.c:714
#, c-format
msgid "while creating return value"
msgstr "beim Erzeugen des Rückgabewerts"

#: plpy_exec.c:738
#, c-format
msgid "could not create new dictionary while building trigger arguments"
msgstr "konnte neues Dictionary nicht erzeugen, beim Aufbauen der Triggerargumente"

#: plpy_exec.c:927
#, c-format
msgid "TD[\"new\"] deleted, cannot modify row"
msgstr "TD[\"new\"] wurde gelöscht, kann Zeile nicht ändern"

#: plpy_exec.c:932
#, c-format
msgid "TD[\"new\"] is not a dictionary"
msgstr "TD[\"new\"] ist kein Dictionary"

#: plpy_exec.c:957
#, c-format
msgid "TD[\"new\"] dictionary key at ordinal position %d is not a string"
msgstr "Dictionary-Schlüssel auf Position %d in TD[\"new\"] ist keine Zeichenkette"

#: plpy_exec.c:964
#, c-format
msgid "key \"%s\" found in TD[\"new\"] does not exist as a column in the triggering row"
msgstr "in TD[\"new\"] gefundener Schlüssel »%s« existiert nicht als Spalte in der den Trigger auslösenden Zeile"

#: plpy_exec.c:1044
#, c-format
msgid "while modifying trigger row"
msgstr "beim Ändern der Triggerzeile"

#: plpy_exec.c:1105
#, c-format
msgid "forcibly aborting a subtransaction that has not been exited"
msgstr "Abbruch einer Subtransaktion, die nicht beendet wurde, wird erzwungen"

#: plpy_main.c:125
#, c-format
msgid "multiple Python libraries are present in session"
msgstr "in dieser Sitzung sind mehrere Python-Bibliotheken präsent"

#: plpy_main.c:126
#, c-format
msgid "Only one Python major version can be used in one session."
msgstr "Nur eine Python-Hauptversion kann in einer Sitzung verwendet werden."

#: plpy_main.c:142
#, c-format
msgid "untrapped error in initialization"
msgstr "nicht abgefangener Fehler bei der Initialisierung"

#: plpy_main.c:165
#, c-format
msgid "could not import \"__main__\" module"
msgstr "konnte Modul »__main__« nicht importieren"

#: plpy_main.c:170
#, c-format
msgid "could not create globals"
msgstr "konnte globale Objekte nicht erzeugen"

#: plpy_main.c:174
#, c-format
msgid "could not initialize globals"
msgstr "konnte globale Objekte nicht initialisieren"

#: plpy_main.c:389
#, c-format
msgid "PL/Python function \"%s\""
msgstr "PL/Python-Funktion »%s«"

#: plpy_main.c:396
#, c-format
msgid "PL/Python anonymous code block"
msgstr "anonymer PL/Python-Codeblock"

#: plpy_planobject.c:123
#, c-format
msgid "plan.status takes no arguments"
msgstr "plan.status nimmt keine Argumente"

#: plpy_plpymodule.c:178 plpy_plpymodule.c:181
#, c-format
msgid "could not import \"plpy\" module"
msgstr "konnte Modul »plpy« nicht importieren"

#: plpy_plpymodule.c:196
#, c-format
msgid "could not add the spiexceptions module"
msgstr "konnte das Modul »spiexceptions« nicht hinzufügen"

#: plpy_plpymodule.c:217
#, c-format
msgid "could not create the base SPI exceptions"
msgstr "konnte die SPI-Basisausnahmen nicht erzeugen"

#: plpy_plpymodule.c:252 plpy_plpymodule.c:256
#, c-format
msgid "could not generate SPI exceptions"
msgstr "konnte SPI-Ausnahmen nicht erzeugen"

#: plpy_plpymodule.c:422
#, c-format
msgid "could not unpack arguments in plpy.elog"
msgstr "konnte Argumente in plpy.elog nicht entpacken"

#: plpy_plpymodule.c:431
msgid "could not parse error message in plpy.elog"
msgstr "konnte Fehlermeldung in plpy.elog nicht parsen"

#: plpy_plpymodule.c:448
#, c-format
msgid "Argument 'message' given by name and position"
msgstr "Argument »message« wurde durch Namen und Position angegeben"

#: plpy_plpymodule.c:475
#, c-format
msgid "'%s' is an invalid keyword argument for this function"
msgstr "»%s« ist ein ungültiges Schlüsselwortargument für diese Funktion"

#: plpy_plpymodule.c:486 plpy_plpymodule.c:492
#, c-format
msgid "invalid SQLSTATE code"
msgstr "ungültiger SQLSTATE-Code"

#: plpy_procedure.c:232
#, c-format
msgid "trigger functions can only be called as triggers"
msgstr "Triggerfunktionen können nur als Trigger aufgerufen werden"

#: plpy_procedure.c:237
#, c-format
msgid "PL/Python functions cannot return type %s"
msgstr "PL/Python-Funktionen können keinen Rückgabetyp %s haben"

#: plpy_procedure.c:318
#, c-format
msgid "PL/Python functions cannot accept type %s"
msgstr "PL/Python-Funktionen können Typ %s nicht annehmen"

#: plpy_procedure.c:414
#, c-format
msgid "could not compile PL/Python function \"%s\""
msgstr "konnte PL/Python-Funktion »%s« nicht kompilieren"

#: plpy_procedure.c:417
#, c-format
msgid "could not compile anonymous PL/Python code block"
msgstr "konnte anonymen PL/Python-Codeblock nicht kompilieren"

#: plpy_resultobject.c:145 plpy_resultobject.c:165 plpy_resultobject.c:185
#, c-format
msgid "command did not produce a result set"
msgstr "Befehl hat keine Ergebnismenge erzeugt"

#: plpy_spi.c:60
#, c-format
msgid "second argument of plpy.prepare must be a sequence"
msgstr "zweites Argument von plpy.prepare muss eine Sequenz sein"

#: plpy_spi.c:118
#, c-format
msgid "plpy.prepare: type name at ordinal position %d is not a string"
msgstr "plpy.prepare: Typname auf Position %d ist keine Zeichenkette"

#: plpy_spi.c:194
#, c-format
msgid "plpy.execute expected a query or a plan"
msgstr "plpy.execute hat eine Anfrage oder einen Plan erwartet"

#: plpy_spi.c:213
#, c-format
msgid "plpy.execute takes a sequence as its second argument"
msgstr "plpy.execute nimmt eine Sequenz als zweites Argument"

#: plpy_spi.c:337
#, c-format
msgid "SPI_execute_plan failed: %s"
msgstr "SPI_execute_plan fehlgeschlagen: %s"

#: plpy_spi.c:379
#, c-format
msgid "SPI_execute failed: %s"
msgstr "SPI_execute fehlgeschlagen: %s"

#: plpy_subxactobject.c:123
#, c-format
msgid "this subtransaction has already been entered"
msgstr "diese Subtransaktion wurde bereits begonnen"

#: plpy_subxactobject.c:129 plpy_subxactobject.c:187
#, c-format
msgid "this subtransaction has already been exited"
msgstr "diese Subtransaktion wurde bereits beendet"

#: plpy_subxactobject.c:181
#, c-format
msgid "this subtransaction has not been entered"
msgstr "diese Subtransaktion wurde nicht begonnen"

#: plpy_subxactobject.c:193
#, c-format
msgid "there is no subtransaction to exit from"
msgstr "es gibt keine Subtransaktion zu beenden"

#: plpy_typeio.c:286
#, c-format
msgid "could not create new dictionary"
msgstr "konnte neues Dictionary nicht erzeugen"

#: plpy_typeio.c:560
#, c-format
msgid "could not import a module for Decimal constructor"
msgstr "konnte kein Modul für den »Decimal«-Konstruktor importieren"

#: plpy_typeio.c:564
#, c-format
msgid "no Decimal attribute in module"
msgstr "kein Attribut »Decimal« im Modul"

#: plpy_typeio.c:570
#, c-format
msgid "conversion from numeric to Decimal failed"
msgstr "Umwandlung von numeric in Decimal fehlgeschlagen"

#: plpy_typeio.c:645
#, c-format
msgid "cannot convert multidimensional array to Python list"
msgstr "kann mehrdimensionales Array nicht in Python-Liste umwandeln"

#: plpy_typeio.c:646
#, c-format
msgid "PL/Python only supports one-dimensional arrays."
msgstr "PL/Python unterstützt nur eindimensionale Arrays."

#: plpy_typeio.c:652
#, c-format
msgid "could not create new Python list"
msgstr "konnte neue Python-Liste nicht erzeugen"

#: plpy_typeio.c:711
#, c-format
msgid "could not create bytes representation of Python object"
msgstr "konnte Bytes-Darstellung eines Python-Objektes nicht erzeugen"

#: plpy_typeio.c:822
#, c-format
msgid "could not create string representation of Python object"
msgstr "konnte Zeichenkettendarstellung eines Python-Objektes nicht erzeugen"

#: plpy_typeio.c:833
#, c-format
msgid "could not convert Python object into cstring: Python string representation appears to contain null bytes"
msgstr "konnte Python-Objekt nicht in cstring umwandeln: Python-Zeichenkettendarstellung enthält anscheinend Null-Bytes"

#: plpy_typeio.c:879
#, c-format
msgid "return value of function with array return type is not a Python sequence"
msgstr "Rückgabewert von Funktion mit Array-Rückgabetyp ist keine Python-Sequenz"

#: plpy_typeio.c:1000
#, c-format
msgid "key \"%s\" not found in mapping"
msgstr "Schlüssel »%s« nicht in Mapping gefunden"

#: plpy_typeio.c:1001
#, c-format
msgid "To return null in a column, add the value None to the mapping with the key named after the column."
msgstr "Um einen NULL-Wert in einer Spalte zurückzugeben, muss der Wert None mit einem nach der Spalte benannten Schlüssel in das Mapping eingefügt werden."

#: plpy_typeio.c:1052
#, c-format
msgid "length of returned sequence did not match number of columns in row"
msgstr "Länge der zurückgegebenen Sequenz hat nicht mit der Anzahl der Spalten in der Zeile übereingestimmt"

#: plpy_typeio.c:1163
#, c-format
msgid "attribute \"%s\" does not exist in Python object"
msgstr "Attribut »%s« existiert nicht in Python-Objekt"

#: plpy_typeio.c:1164
#, c-format
msgid "To return null in a column, let the returned object have an attribute named after column with value None."
msgstr "Um einen NULL-Wert in einer Spalte zurückzugeben, muss das zurückzugebende Objekt ein nach der Spalte benanntes Attribut mit dem Wert None haben."

#: plpy_util.c:36
#, c-format
msgid "could not convert Python Unicode object to bytes"
msgstr "konnte Python-Unicode-Objekt nicht in Bytes umwandeln"

#: plpy_util.c:42
#, c-format
msgid "could not extract bytes from encoded string"
msgstr "konnte kodierte Zeichenkette nicht in Bytes umwandeln"
