# Spanish message translation file for plpython
#
# Copyright (C) 2009-2012 PostgreSQL Global Development Group
# This file is distributed under the same license as the PostgreSQL package.
#
# Emanuel Calvo Franco <postgres.arg@gmail.com>, 2009.
# Alvaro Herrera <alvherre@alvh.no-ip.org>, 2009-2012
#
msgid ""
msgstr ""
"Project-Id-Version: plpython (PostgreSQL 9.6)\n"
"Report-Msgid-Bugs-To: pgsql-bugs@postgresql.org\n"
"POT-Creation-Date: 2016-05-02 20:07+0000\n"
"PO-Revision-Date: 2016-05-25 12:29-0500\n"
"Last-Translator: Carlos Chapi <carlos.chapi@2ndquadrant.com>\n"
"Language-Team: PgSQL-es-Ayuda <pgsql-es-ayuda@postgresql.org>\n"
"Language: es\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Generator: Poedit 1.8.7\n"

#: plpy_cursorobject.c:101
#, c-format
msgid "plpy.cursor expected a query or a plan"
msgstr "plpy.cursor espera una consulta o un plan"

#: plpy_cursorobject.c:179
#, c-format
msgid "plpy.cursor takes a sequence as its second argument"
msgstr "plpy.cursor lleva una secuencia como segundo argumento"

#: plpy_cursorobject.c:195 plpy_spi.c:229
#, c-format
msgid "could not execute plan"
msgstr "no se pudo ejecutar el plan"

#: plpy_cursorobject.c:198 plpy_spi.c:232
#, c-format
msgid "Expected sequence of %d argument, got %d: %s"
msgid_plural "Expected sequence of %d arguments, got %d: %s"
msgstr[0] "Se esperaba una secuencia de %d argumento, se obtuvo %d: %s"
msgstr[1] "Se esperaba una secuencia de %d argumentos, se obtuvo %d: %s"

#: plpy_cursorobject.c:354
#, c-format
msgid "iterating a closed cursor"
msgstr "iterando un cursor cerrado"

#: plpy_cursorobject.c:362 plpy_cursorobject.c:427
#, c-format
msgid "iterating a cursor in an aborted subtransaction"
msgstr "iterando un cursor en una subtransacción abortada"

#: plpy_cursorobject.c:419
#, c-format
msgid "fetch from a closed cursor"
msgstr "haciendo «fetch» en un cursor cerrado"

#: plpy_cursorobject.c:467 plpy_spi.c:438
#, c-format
msgid "query result has too many rows to fit in a Python list"
msgstr "el resultado de la consulta tiene demasiados registros y no entran en una lista de Python"

#: plpy_cursorobject.c:508
#, c-format
msgid "closing a cursor in an aborted subtransaction"
msgstr "cerrando un cursor en una subtransacción abortada"

#: plpy_elog.c:127 plpy_elog.c:128 plpy_plpymodule.c:513
#, c-format
msgid "%s"
msgstr "%s"

#: plpy_exec.c:140
#, c-format
msgid "unsupported set function return mode"
msgstr "modo de retorno de conjunto de función no soportado"

#: plpy_exec.c:141
#, c-format
msgid "PL/Python set-returning functions only support returning one value per call."
msgstr "Las funciones PL/Python que retornan conjuntos sólo permiten retornar un valor por invocación."

#: plpy_exec.c:154
#, c-format
msgid "returned object cannot be iterated"
msgstr "objeto retornado no puede ser iterado"

#: plpy_exec.c:155
#, c-format
msgid "PL/Python set-returning functions must return an iterable object."
msgstr "Los funciones PL/Python que retornan conjuntos deben retornar un objeto iterable."

#: plpy_exec.c:169
#, c-format
msgid "error fetching next item from iterator"
msgstr "error extrayendo el próximo elemento del iterador"

#: plpy_exec.c:210
#, c-format
msgid "PL/Python function with return type \"void\" did not return None"
msgstr "función PL/Python con tipo de retorno «void» no retorna None"

#: plpy_exec.c:374 plpy_exec.c:400
#, c-format
msgid "unexpected return value from trigger procedure"
msgstr "valor de retorno no esperado desde el procedimiento disparador"

#: plpy_exec.c:375
#, c-format
msgid "Expected None or a string."
msgstr "Se esperaba None o una cadena."

#: plpy_exec.c:390
#, c-format
msgid "PL/Python trigger function returned \"MODIFY\" in a DELETE trigger -- ignored"
msgstr "función de disparador de PL/Python retorno «MODIFY» en un disparador de tipo DELETE -- ignorado"

#: plpy_exec.c:401
#, c-format
msgid "Expected None, \"OK\", \"SKIP\", or \"MODIFY\"."
msgstr "Se esperaba None, «OK», «SKIP» o «MODIFY»."

#: plpy_exec.c:482
#, c-format
msgid "PyList_SetItem() failed, while setting up arguments"
msgstr "PyList_SetItem() falló, mientras se inicializaban los argumentos"

#: plpy_exec.c:486
#, c-format
msgid "PyDict_SetItemString() failed, while setting up arguments"
msgstr "PyDict_SetItemString() falló, mientras se inicializaban los argumentos"

#: plpy_exec.c:498
#, c-format
msgid "function returning record called in context that cannot accept type record"
msgstr "se llamó una función que retorna un registro en un contexto que no puede aceptarlo"

#: plpy_exec.c:714
#, c-format
msgid "while creating return value"
msgstr "mientras se creaba el valor de retorno"

#: plpy_exec.c:738
#, c-format
msgid "could not create new dictionary while building trigger arguments"
msgstr "no se pudo crear un nuevo diccionario mientras se construían los argumentos de disparador"

#: plpy_exec.c:927
#, c-format
msgid "TD[\"new\"] deleted, cannot modify row"
msgstr "TD[\"new\"] borrado, no se puede modicar el registro"

#: plpy_exec.c:932
#, c-format
msgid "TD[\"new\"] is not a dictionary"
msgstr "TD[\"new\"] no es un diccionario"

#: plpy_exec.c:957
#, c-format
msgid "TD[\"new\"] dictionary key at ordinal position %d is not a string"
msgstr "el nombre del atributo de TD[\"new\"] en la posición %d no es una cadena"

#: plpy_exec.c:964
#, c-format
msgid "key \"%s\" found in TD[\"new\"] does not exist as a column in the triggering row"
msgstr "la llave «%s» en TD[\"new\"] no existe como columna en la fila disparadora"

#: plpy_exec.c:1044
#, c-format
msgid "while modifying trigger row"
msgstr "mientras se modificaba la fila de disparador"

# FIXME not very happy with this
#: plpy_exec.c:1105
#, c-format
msgid "forcibly aborting a subtransaction that has not been exited"
msgstr "abortando una subtransacción que no se ha cerrado"

#: plpy_main.c:125
#, c-format
msgid "multiple Python libraries are present in session"
msgstr "hay múltiples librerías de Python presentes en esta sesión"

#: plpy_main.c:126
#, c-format
msgid "Only one Python major version can be used in one session."
msgstr "Sólo se puede usar una versión mayor de Python en cada sesión."

#: plpy_main.c:142
#, c-format
msgid "untrapped error in initialization"
msgstr "error no capturado en la inicialización"

#: plpy_main.c:165
#, c-format
msgid "could not import \"__main__\" module"
msgstr "no se pudo importar el módulo «__main__»"

#: plpy_main.c:170
#, c-format
msgid "could not create globals"
msgstr "no se pudo crear las globales"

#: plpy_main.c:174
#, c-format
msgid "could not initialize globals"
msgstr "no se pudo inicializar las globales"

#: plpy_main.c:389
#, c-format
msgid "PL/Python function \"%s\""
msgstr "función PL/Python «%s»"

#: plpy_main.c:396
#, c-format
msgid "PL/Python anonymous code block"
msgstr "bloque de código anónimo de PL/Python"

#: plpy_planobject.c:123
#, c-format
msgid "plan.status takes no arguments"
msgstr "plan.status no lleva argumentos"

#: plpy_plpymodule.c:178 plpy_plpymodule.c:181
#, c-format
msgid "could not import \"plpy\" module"
msgstr "no se pudo importar el módulo «plpy»"

#: plpy_plpymodule.c:196
#, c-format
msgid "could not add the spiexceptions module"
msgstr "no se pudo importar el módulo spiexceptions"

#: plpy_plpymodule.c:217
#, c-format
msgid "could not create the base SPI exceptions"
msgstr "no se pudo crear las excepciones SPI basales"

#: plpy_plpymodule.c:252 plpy_plpymodule.c:256
#, c-format
msgid "could not generate SPI exceptions"
msgstr "no se pudo generar excepciones SPI"

#: plpy_plpymodule.c:421
#, c-format
msgid "could not unpack arguments in plpy.elog"
msgstr "no se pudo desempaquetar los argumentos de plpy.elog"

#: plpy_plpymodule.c:430
msgid "could not parse error message in plpy.elog"
msgstr "no se pudo analizar el mensaje de error de plpy.elog"

#: plpy_plpymodule.c:446
#, c-format
msgid "the message is already specified"
msgstr "el mensaje ya está definido"

#: plpy_plpymodule.c:469
#, c-format
msgid "'%s' is an invalid keyword argument for this function"
msgstr "«%s» no es un argumento válido para esta función"

#: plpy_plpymodule.c:477 plpy_plpymodule.c:480
#, c-format
msgid "invalid SQLSTATE code"
msgstr "código SQLSTATE no válido"

#: plpy_procedure.c:232
#, c-format
msgid "trigger functions can only be called as triggers"
msgstr "las funciones disparadoras sólo pueden ser llamadas como disparadores"

#: plpy_procedure.c:237
#, c-format
msgid "PL/Python functions cannot return type %s"
msgstr "las funciones PL/Python no pueden retornar el tipo %s"

#: plpy_procedure.c:318
#, c-format
msgid "PL/Python functions cannot accept type %s"
msgstr "la funciones PL/Python no pueden aceptar el tipo %s"

#: plpy_procedure.c:414
#, c-format
msgid "could not compile PL/Python function \"%s\""
msgstr "no se pudo compilar la función PL/Python «%s»"

#: plpy_procedure.c:417
#, c-format
msgid "could not compile anonymous PL/Python code block"
msgstr "no se pudo compilar el bloque anónimo PL/Python"

#: plpy_resultobject.c:145 plpy_resultobject.c:165 plpy_resultobject.c:185
#, c-format
msgid "command did not produce a result set"
msgstr "la orden no produjo un conjunto de resultados"

#: plpy_spi.c:60
#, c-format
msgid "second argument of plpy.prepare must be a sequence"
msgstr "el segundo argumento de plpy.prepare debe ser una secuencia"

#: plpy_spi.c:118
#, c-format
msgid "plpy.prepare: type name at ordinal position %d is not a string"
msgstr "plpy.prepare: el nombre de tipo en la posición %d no es una cadena"

#: plpy_spi.c:194
#, c-format
msgid "plpy.execute expected a query or a plan"
msgstr "plpy.execute espera una consulta o un plan"

#: plpy_spi.c:213
#, c-format
msgid "plpy.execute takes a sequence as its second argument"
msgstr "plpy.execute lleva una secuencia como segundo argumento"

#: plpy_spi.c:337
#, c-format
msgid "SPI_execute_plan failed: %s"
msgstr "falló SPI_execute_plan: %s"

#: plpy_spi.c:379
#, c-format
msgid "SPI_execute failed: %s"
msgstr "falló SPI_execute: %s"

#: plpy_subxactobject.c:123
#, c-format
msgid "this subtransaction has already been entered"
msgstr "ya se ha entrado en esta subtransacción"

#: plpy_subxactobject.c:129 plpy_subxactobject.c:187
#, c-format
msgid "this subtransaction has already been exited"
msgstr "ya se ha salido de esta subtransacción"

#: plpy_subxactobject.c:181
#, c-format
msgid "this subtransaction has not been entered"
msgstr "no se ha entrado en esta subtransacción"

#: plpy_subxactobject.c:193
#, c-format
msgid "there is no subtransaction to exit from"
msgstr "no hay una subtransacción de la cual salir"

#: plpy_typeio.c:286
#, c-format
msgid "could not create new dictionary"
msgstr "no se pudo crear un nuevo diccionario"

#: plpy_typeio.c:560
#, c-format
msgid "could not import a module for Decimal constructor"
msgstr "no se pudo importar un módulo para el constructor Decimal"

#: plpy_typeio.c:564
#, c-format
msgid "no Decimal attribute in module"
msgstr "no se encontró atributo Decimal en el módulo"

#: plpy_typeio.c:570
#, c-format
msgid "conversion from numeric to Decimal failed"
msgstr "falló la conversión de numeric a Decimal"

#: plpy_typeio.c:645
#, c-format
msgid "cannot convert multidimensional array to Python list"
msgstr "no se puede convertir array multidimensional a una lista Python"

#: plpy_typeio.c:646
#, c-format
msgid "PL/Python only supports one-dimensional arrays."
msgstr "PL/Python sólo soporta arrays unidimensionales."

#: plpy_typeio.c:652
#, c-format
msgid "could not create new Python list"
msgstr "no se pudo crear una nueva lista Python"

#: plpy_typeio.c:711
#, c-format
msgid "could not create bytes representation of Python object"
msgstr "no se pudo crear la representación de cadena de bytes de Python"

#: plpy_typeio.c:822
#, c-format
msgid "could not create string representation of Python object"
msgstr "no se pudo crear la representación de cadena de texto del objeto de Python"

#: plpy_typeio.c:833
#, c-format
msgid "could not convert Python object into cstring: Python string representation appears to contain null bytes"
msgstr "no se pudo convertir el objeto Python a un cstring: la representación de cadena Python parece tener bytes nulos (\\0)"

#: plpy_typeio.c:879
#, c-format
msgid "return value of function with array return type is not a Python sequence"
msgstr "el valor de retorno de la función con tipo de retorno array no es una secuencia Python"

#: plpy_typeio.c:1000
#, c-format
msgid "key \"%s\" not found in mapping"
msgstr "la llave «%s» no fue encontrada en el mapa"

#: plpy_typeio.c:1001
#, c-format
msgid "To return null in a column, add the value None to the mapping with the key named after the column."
msgstr "Para retornar null en una columna, agregue el valor None al mapa, con llave llamada igual que la columna."

#: plpy_typeio.c:1052
#, c-format
msgid "length of returned sequence did not match number of columns in row"
msgstr "el tamaño de la secuencia retornada no concuerda con el número de columnas de la fila"

#: plpy_typeio.c:1163
#, c-format
msgid "attribute \"%s\" does not exist in Python object"
msgstr "el atributo «%s» no existe en el objeto Python"

#: plpy_typeio.c:1164
#, c-format
msgid "To return null in a column, let the returned object have an attribute named after column with value None."
msgstr "Para retornar null en una columna, haga que el objeto retornado tenga un atributo llamado igual que la columna, con valor None."

#: plpy_util.c:36
#, c-format
msgid "could not convert Python Unicode object to bytes"
msgstr "no se pudo convertir el objeto Unicode de Python a bytes"

#: plpy_util.c:42
#, c-format
msgid "could not extract bytes from encoded string"
msgstr "no se pudo extraer bytes desde la cadena codificada"

#~ msgid "PL/Python does not support conversion to arrays of row types."
#~ msgstr "PL/Python no soporta la conversión de arrays a tipos de registro."

#~ msgid "plpy.prepare does not support composite types"
#~ msgstr "plpy.prepare no soporta tipos compuestos"

#~ msgid "Start a new session to use a different Python major version."
#~ msgstr "Inicie una nueva sesión para usar una versión mayor de Python diferente."

#~ msgid "This session has previously used Python major version %d, and it is now attempting to use Python major version %d."
#~ msgstr "Esta sesión ha usado previamente la versión mayor de Python %d, y ahora está intentando usar la versión mayor %d."
